### ISSUE TITLE
Incorrect free space when using LVM RAID

### ISSUE THREAD

**Issue by da2x** [storaged-project/blivet-gui#107]
1. Add two 1 TB PVs to a new VG. Add one LV of 1 TB of type RAID1 to that VG. You now have two identical disks and have consumed all available space in that VG.
2. Open blivet-gui and select your VG.

Logical View will display one LV of 1 TB and incorrectly show 1 TB of “free space”.

You can create new LVs in that free space. I’ve not tested what happens if you attempt that.

**Comment by vojtechtrefny** [comment]
This is actually bug in LVM -- https://bugzilla.redhat.com/show_bug.cgi?id=1608930
But we also have another issue in blivet that made the LVM bug worse (https://github.com/storaged-project/blivet/pull/709)

**Comment by vojtechtrefny** [comment]
The blivet issue was fixed a long time ago so this should be also fixed in blivet-gui now.
