### ISSUE TITLE
Update readme to better reflect current porting status

### ISSUE THREAD

**Issue by ghost** [storaged-project/blivet-gui#118]
Readme states that "Main dependencies include blivet, libblockdev and libbytesize. Note that these are probably not packaged for other distributions than Fedora." which seems to be no longer the case for libraries according to https://repology.org/metapackage/libbytesize/versions and https://repology.org/metapackage/libblockdev/versions So the only real showstopper is blivet itself.

**Comment by vojtechtrefny** [comment]
Fixed. Manual installation instruction have been moved to the [wiki](https://github.com/storaged-project/blivet-gui/wiki).
