### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [storaged-project/blivet-gui#145]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by vojtechtrefny** [comment]
> [mandatory] which branch is your development branch?

master

> [mandatory] have you merged latest translation from Zanata and locked the project?

The Zanata project is read-only now. Pull request with latest PO files is not merged yet (#146)

> [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

Same as the code `GPL-2.0-or-later` probably. (Is there a reason to have a different licence? What's the default licence for translations from Zanata?)

> [optional] do you need us to activate any specific checks? (this is a setting per component [3])

Python format, Python brace format

> [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No.

**Comment by vojtechtrefny** [comment]
The PR with PO files is merged now.

**Comment by Jibec** [comment]
done: https://translate.fedoraproject.org/projects/blivet/blivet-gui/

Weblate will update po files when a pot file is updated
Weblate will open a PR and squash commits per autor

please reach https://lists.fedoraproject.org/archives/list/trans%40lists.fedoraproject.org/ and https://pagure.io/fedora-l10n/tickets for support or issues
