### ISSUE TITLE
"Edit selected device" toolbar menu and "Edit" context menu inconsistent

### ISSUE THREAD

**Issue by ferdnyc** [storaged-project/blivet-gui#176]
Though they appear to have identical purpose and function, the menu displayed when clicking the "Edit selected device" toolbar button has a completely different ordering from the "Edit" submenu of the device's context menu. That's just confusing, and forces the user to have to search for the option they're looking for each time through, because it isn't always where they expect it to be.

Screenshots from `blivet-gui` installed via `blivet-gui-2.1.12-1.fc31.noarch` RPM on Fedora 31:

![Screenshot from 2020-05-06 01-25-11](https://user-images.githubusercontent.com/538020/81140796-b4a6eb00-8f38-11ea-88e2-ff37530ba936.png)
![Screenshot from 2020-05-06 01-25-07](https://user-images.githubusercontent.com/538020/81140799-b7094500-8f38-11ea-8698-9924c6b31d95.png)

(OK, it's just one item moved in the ordering, but that results in every option except the first two (**Edit:** and the last) being in a different place in each of the two menus.)

**Comment by vojtechtrefny** [comment]
I agree this could be confusing, I moved the set label option in the right click menu to match the edit button menu in #177 Thank you for the report.
