### ISSUE TITLE
"looking up parted Partition" - uses "/dev/md/md128p1" instead of "/dev/md/128p1"

### ISSUE THREAD

**Issue by leo-lb** [storaged-project/blivet-gui#226]
Hello!

On my Fedora 32 system blivet-gui 2.1.15 fails to open

```
INFO:blivet: scanning md128p1 (/sys/devices/virtual/block/md128/md128p1)...
DEBUG:blivet:                            DeviceTree.get_device_by_name returned None
DEBUG:blivet:                             DeviceTree.get_device_by_name returned None
DEBUG:blivet: existing RAID raid1 size == 3.64 TiB
DEBUG:blivet:                             DeviceTree.get_device_by_name returned existing 3.64 TiB mdarray 128 (127) with existing gpt disklabel
DEBUG:blivet: get_format('None') returning DeviceFormat instance with object id 352
DEBUG:blivet: get_format('None') returning DeviceFormat instance with object id 353
DEBUG:blivet: looking up parted Partition: /dev/md/md128p1
ERROR:blivet: Failed to instantiate PartitionDevice: ('cannot find parted partition instance', 'md128p1')
DEBUG:blivet: no device obtained for md128p1
DEBUG:blivet:                          DeviceTree.get_device_by_name returned None
```

It tries to look up `/dev/md/md128p1` but that does not exist, on the other hand `/dev/md/128p1` does exist

I am guessing there's confusion in the code somewhere on whether or not to prefix with `md`, but I could not find where.

I am relunctant to sharing full logs because they contain lots of sensitive information, I think what I sent should be sufficient.

Thank you!

**Comment by leo-lb** [comment]
Nevermind, probably will be solved by: https://github.com/storaged-project/blivet/pull/888

I am testing this PR on my system as we speak!

**Comment by leo-lb** [comment]
I can confirm, the PR does fix the issue! Thanks a lot @vojtechtrefny !

**Comment by vojtechtrefny** [comment]
Thank you for testing the fix.
