### ISSUE TITLE
f2fs support

### ISSUE THREAD

**Issue by Ygarr** [storaged-project/blivet-gui#252]
In information window just "Type: none" on f2fs partition

**Comment by vojtechtrefny** [comment]
What version of blivet do you have? Support for F2FS was added in 3.3.0: https://github.com/storaged-project/blivet/pull/876

**Comment by Ygarr** [comment]
May be Manjaro linux does not support fresh versions at all?:
![image](https://user-images.githubusercontent.com/14309871/103042290-cef20f80-4581-11eb-8869-9dbbec18321f.png)

**Comment by vojtechtrefny** [comment]
blivet 3.2.2 was released in May so Manjaro/Arch isn't that far behind. I'm closing this now, it's unfortunate that blivet needs a special support for every filesystem, but there's nothing I can do about it for older versions :-(
