### ISSUE TITLE
Unable to delete btrfs volume that has subvolumes

### ISSUE THREAD

**Issue by ludwigd** [storaged-project/blivet-gui#261]
A btrfs volume cannot be deleted until all subvolumes are deleted. As the subvolumes have to be deleted one by one, this can be very annoying if you have many of them (for example created by snapper or timeshift). 

Deleting the parent volume should ask for permission to auto-remove existing subvolumes.

To reproduce, fire up a the Fedora installer in a VM and choose "Advanced Partitioning (Blivet Gui)". Create a Btrfs Volume with some subvolumes and try to delete the parent volume. See attached screenshots.

A. Btrfs Volume with subvolumes has 'Delete' deactivated.
![Screenshot from 2021-01-20 10-20-45](https://user-images.githubusercontent.com/1677987/105155724-38c2f200-5b0b-11eb-81e0-8e79a4fe7fbb.png)

B. Btrfs Volume without subvolumes can be deleted
![Screenshot from 2021-01-20 10-21-57](https://user-images.githubusercontent.com/1677987/105155750-40829680-5b0b-11eb-9abe-ef7cdda0d0d4.png)

**Comment by vojtechtrefny** [comment]
This is actually already implemented and will be available in next release, see https://github.com/storaged-project/blivet-gui/pull/245

Feels nice to be actually one step ahead of RFEs for once :-)
