### ISSUE TITLE
GPG key expired on build.opensuse.org

### ISSUE THREAD

**Issue by DanielGlaas** [storaged-project/blivet-gui#284]
Hi,

I installed blivet-gui on Ubuntu 20.04 via apt, offered on https://build.opensuse.org/package/show/home%3Avtrefny/blivet-gui. I did it with these steps: https://software.opensuse.org/download/package?package=blivet-gui&project=home%3Avtrefny

Unfortunately this does not work anymore, as the key expired on 2021-06-24.
It would be very kind of you could add an updated [Release.key](http://download.opensuse.org/repositories/home:/vtrefny/xUbuntu_20.04/Release.key) to the repository.

`sudo apt-key list` gives:
> /etc/apt/trusted.gpg.d/home_vtrefny.gpg
>
> pub   rsa2048 2014-11-17 [SC] [verfallen: 2021-06-24]
>      6A0C B0C1 5429 613E EC03  49B5 70F7 2613 FAEF 25AF
> uid        [ verfallen] home:vtrefny OBS Project <home:vtrefny@build.opensuse.org>

Note: "verfallen" is German for "expired"

Thank you!

**Comment by vojtechtrefny** [comment]
I did a new build in the repo and the key was updated automatically. I hope it foxed the issue for you, I had to remove and re-add the repo on my testing VM.

**Comment by DanielGlaas** [comment]
Yes, with the new key the issue is fixed!
Thank you for this quick reaction.

However, it was not that straight forward to update the key. The outdated key was stored in file `/etc/apt/trusted.gpg,` which means that downloading the new key into file `/etc/apt/trusted.gpg.d/home_vtrefny.gpg` did not solve the problem as the old key was still present. I had to remove it with this command:
`sudo apt-key del 70F72613FAEF25AF`

I post my commands here in case someone else stumbles about this problem:
