### ISSUE TITLE
[UI Bug]

### ISSUE THREAD

**Issue by ThellraAK** [storaged-project/blivet-gui#311]
I'm on Debian unstable with KDE, and installed blivit-gui using the [opensuse repo thing here](https://software.opensuse.org/download.html?project=home:vtrefny&package=blivet-gui)

![image](https://user-images.githubusercontent.com/13631482/146562875-46dd687e-c322-46b5-91fd-ad3df1a52a2f.png)

I can't think of a good way to show you the image other then that.

![image](https://user-images.githubusercontent.com/13631482/146563810-24d6ac33-8df1-4645-a6da-e4822f91cdc8.png)

Is what it looks like maximized on my 1600x900 monitor, in order to see the buttons to save/sweep/undo/threebarsoption thing, I had to widen the application, drag it over to the edge and repeat until I'd nearly doubled it's size.

Don't know if it makes a difference, but it happens for both launching from terminal, and the application launcher.

**Comment by vojtechtrefny** [comment]
Thank you for the report. Do you see something that could cause this in the logical view (partition list) -- for example a long name or filesystem label that overflows some of the UI elements or simply doesn't fit?

I'll try to look at the UI template for the main windows, maybe there is something obviously wrong with the elements and their size limits, but I've never seen something similar. And your storage setup looks very simple from what I can see so there shouldn't be any surprises like 1000 devices that cause the UI to do this.

**Comment by ThellraAK** [comment]
I'll try this tonight, sorry I missed the original notification, didn't
mean to hit and run.

Maybe if they were grabbing the thinpool vg and the vg and the and the,
maybe would have added up to being that long

**Comment by vojtechtrefny** [comment]
I was randomly able to reproduce this when I was testing some btrfs fixes. It wasn't as bad as your case (making the window fullscreen fixed it for me), so it is possible there is something else wrong, feel free to reopen the issue if this doesn't fix it for you.

You can test the fix by cloning the git repository and starting blivet-gui from the folder with `PYTHONPATH=. PATH=`pwd`:$PATH blivet-gui`.
