### ISSUE TITLE
Let the user create nested BTRFS subvolumes

### ISSUE THREAD

**Issue by Firlaev-Hans** [storaged-project/blivet-gui#387]
Something that irritated me recently when installing Fedora is that it is not possible to create a subvolume within another subvolume using Blivet-GUI, **despite the fact that this is actually supported in BTRFS** (and in fact, Blivet-GUI shows existing nested subvolumes in the tree). 
But the '+' icon is greyed out when any subvolume is selected rather than the top level BTRFS volume.

![Screenshot 1](https://user-images.githubusercontent.com/61254500/220151420-6765a319-1209-4e0b-930c-709cfc046f92.png)
The top-level BTRFS volume is selected, thus the + button can be clicked to create a subvolume

![Screenshot 2](https://user-images.githubusercontent.com/61254500/220151422-f59b8218-3c49-4c99-a98f-c81e25517140.png)
A the root subvolume is selected. Note that Blivet-GUI shows several sub-subvolumes of root, but for some reasonthe + button to create another one is greyed out.

My use case for nested subvolumes would be having multiple Linux distros installed on one BTRFS partition (which is unfortunately barely or not at all supported on most distro installers but that's another issue).
My Layout would look something like this:
```
<BTRFS partition>
+Fedora
++rootfs
++home
+KDE-Neon
++rootfs
++home
```

Is there any specific reason why Blivet-GUI prevents this, or is this simply an oversight?

**Comment by vojtechtrefny** [comment]
> Is there any specific reason why Blivet-GUI prevents this, or is this simply an oversight?

No, thee is no reason for this other than I simply didn't know this is a supported use case for subvolumes when I wrote the btrfs support. I'll try to fix this in the next release, this should be a relatively simple change. Thank you for the report.
