### ISSUE TITLE
Public keys for ubuntu repo are expired

### ISSUE THREAD

**Issue by phlummox** [storaged-project/blivet-gui#407]
The README states that https://github.com/storaged-project/blivet-gui/blob/b9d0d304aca95a8e62e5e7406aae055e67420c2a/README.md?plain=1#L32

> "Official packages for Debian and Ubuntu (19.04 and newer) are available in our [Open Build Service repository](https://software.opensuse.org/download.html?project=home:vtrefny&package=blivet-gui)."

However, that repository appears to have an expired public key, and thus cannot be used. Following the instructions from the https://software.opensuse.org repository site for Ubuntu 22.04 –

```
echo 'deb http://download.opensuse.org/repositories/home:/vtrefny/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/home:vtrefny.list
curl -fsSL https://download.opensuse.org/repositories/home:vtrefny/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_vtrefny.gpg > /dev/null
sudo apt update
sudo apt install blivet-gui
```

creates a GPG public key in `/etc/apt/trusted.gpg.d/home_vtrefny.gpg`, and running `apt-key list` shows that the key has expired:

```
/etc/apt/trusted.gpg.d/home_vtrefny.gpg
---------------------------------------
pub   rsa2048 2014-11-17 [SC] [expired: 2023-09-03]
      6A0C B0C1 5429 613E EC03  49B5 70F7 2613 FAEF 25AF
uid           [ expired] home:vtrefny OBS Project <home:vtrefny@build.opensuse.org>
```

Tools like `apt-get` therefore rightly refuse to use the repository because of this. Running `apt-get update` results in the error message:

```
Err:13 http://download.opensuse.org/repositories/home:/vtrefny/xUbuntu_22.04  InRelease
  The following signatures were invalid: EXPKEYSIG 70F72613FAEF25AF home:vtrefny OBS Project <home:vtrefny@build.opensuse.org>
```

If I should report this somewhere else, let me know – but there's no avenue that I can see at https://software.opensuse.org or https://build.opensuse.org for reporting invalid repository keys.

**Comment by vojtechtrefny** [comment]
Thank you for the report, new key is now available in the repository. This unfortunately happens from time to time -- I don't have builds often enough and a new key is created only when a new build is done in the repo.
You now need to remove the old key with `apt-key del home_vtrefny.gpg` and download the new one with `curl -fsSL https://download.opensuse.org/repositories/home:vtrefny/xUbuntu_22.10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_vtrefny.gpg > /dev/null` (there might be a simpler way, but I am not expert on apt).

**Comment by phlummox** [comment]
No worries, thanks for that. Cheers!
