### ISSUE TITLE
Bug reporting does not work

### ISSUE THREAD

**Issue by M4rtinK** [storaged-project/blivet-gui#445]
![20240808_162224](https://github.com/user-attachments/assets/750d43e0-3587-49ea-b211-e7d890223fee)

I've managed to crash Blivet GUI, but when i clicked on the report-bug button, the resulting window did not look actionable. when I closed the window, Blivet GUI also closed.

**Comment by vojtechtrefny** [comment]
This happens with blivet-gui installed from the daily builds repository -- abrt ignores reports from unsigned packages:

```
srp 11 15:56:42 aida abrt-server[9507]: Deleting problem directory '/var/spool/abrt/Python3-2024-08-11-15:56:42-9415'
srp 11 15:56:42 aida abrt-server[9507]: 'post-create' on '/var/spool/abrt/Python3-2024-08-11-15:56:42-9415' exited with 1
srp 11 15:56:42 aida abrt-server[9507]: Package 'blivet-gui-runtime' isn't signed with proper key
srp 11 15:56:42 aida python3[9415]: detected unhandled Python exception in '/usr/bin/blivet-gui'
````

The bug reporting features seems to be working correctly with blivet-gui installed from the system repository on Fedora.
